### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x99 in position 22: invalid start byte

### ISSUE THREAD

**Issue by blueevangelion** [jzbontar/mc-cnn#53]
I had Compute the Matching Cost and be able to run with pretrained network.
I downloaded Middlebury dataset use ./download_middlebury.sh command.
I compile MiddEval3-SDK and installed ImageMagick.
I got the following error while i try to run preprocess_mb.py 

Adirondack
Traceback (most recent call last):
  File "preprocess_mb.py", line 166, in <module>
    disp0, scale0 = load_pfm(os.path.join(base2_imperfect, 'disp0.pfm'), True)
  File "preprocess_mb.py", line 34, in load_pfm
    header = file.readline().rstrip()
  File "/usr/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x99 in position 22: invalid start byte

Opencv version:3.4.0
python version:3.5

**Comment by pannyl** [comment]
Hello, I have the same problem. Could you please tell me how to solved it ?
